### ISSUE TITLE
duplicate functions in PhyloTreePreorder

### ISSUE THREAD

**Issue by xjlizji** [jqujqu/EvoSim#14]
`size_t count_leaves(const std::vector<size_t> &subtree_sizes);`
and
`size_t leafsize(const std::vector<size_t> &subtree_sizes);
`
are same.

**Comment by andrewdavidsmith** [comment]
The second one is strangely named

On May 15, 2018, at 6:51 PM, Liz Ji <notifications@github.com<mailto:notifications@github.com>> wrote:


size_t count_leaves(const std::vector<size_t> &subtree_sizes);
and
size_t leafsize(const std::vector<size_t> &subtree_sizes);
are same.

**Comment by xjlizji** [comment]
The second one was removed.
