### ISSUE TITLE
Symmetry of functions to get state sequences

### ISSUE THREAD

**Issue by andrewdavidsmith** [jqujqu/EvoSim#6]
Right now I see three functions for accessing a state sequence:
```
void get_initial_seq(const std::vector<Path> &paths, std::vector<bool> &seq);
void end_sequence(const std::vector<Path> &paths, std::vector<bool> &seq);
void sequence_at_time(const std::vector<Path> &paths, const double t, std::vector<bool> &seq);
```
None of these are member functions of Path, because they need to use multiple Path objects. The problem is consistency of naming, which reduces speed of coding, and introduces small errors. I think we should make the names consistent, but possibly I don't understand why they have different names. Here are suggestions:
```
get_seq_init
get_seq_end
get_seq_at_time
```
Because of the symmetry of the functions, and the fact that one of them has an additional argument, I feel the time should come either as the first or last argument.

**Comment by jqujqu** [comment]
Names have been changed to improve consistency. These functions probably belonged to the old simulation strategy and are not used currently.

**Comment by andrewdavidsmith** [comment]
I think they are still used when taking a simulation and going back to extract sequences at particular times.

On Apr 26, 2018, at 12:45 PM, Jenny Qu <notifications@github.com<mailto:notifications@github.com>> wrote:


Names have been changed to improve consistency. These functions probably belonged to the old simulation strategy and are not used currently.
