### ISSUE TITLE
Cannot read branch with single child

### ISSUE THREAD

**Issue by xjlizji** [jqujqu/EvoSim#9]
I'm trying to simulate a single branch starting from one root to one leaf: `(C:1)E:0;`, but node C cannot be read when it doesn't have siblings. It can be solved by passing this tree structure instead`(C:1,)E:0;`.
Do we need to detect this type of structure?

**Comment by andrewdavidsmith** [comment]
I think we should check the Newick format, to see if this is allowed. I tried the same thing, and I used `(C:1,D:0.000001)E:0;` which also worked. I prefer to keep this the same as the Newick format. I think the only time we would ever want a non-branching node in a tree is when we are just working with a single edge, which we can treat as a totally separate case.
